name: Math Utility Repo applying CI with Maven  # name : tương đương với console.log ghi lại nhật kí chạy các lệnh

on:
  push:
    branches: [ "main" ]      # Bất kì ai push code lên nhánh main
  pull_request:
    branches: [ "main" ]

jobs:                        # thì tự động thực thi các lệnh dưới đây 
  build:                     # bulid app --> .jar .war bằng cách

    runs-on: ubuntu-latest   # 1. Mượn 1 server bên Mỹ, cài sẵn giùm OS Ubuntu

    steps:
    - uses: actions/checkout@v3    # 2. Có server rồi, dowload code từ GH về server này
    - name: Set up JDK 19  -Mượn JDK 19        # 3. Cho mượn cái JDK
      uses: actions/setup-java@v3
      with:
        java-version: '19'                        # 4. Khai báo version JDK tương ứng với file pom.xml
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven   -Tạo file .jar .war                       # 5. Mượn Maven, chạy lệnh đóng gói, test luôn xanh đỏ
      run: mvn -B package --file pom.xml
